// This File is Auto-Generated by the json-to-gui.js!

#include "LFOPage.h"

namespace VeNo
{
    void LFOPage::setupGui ()
    {
        // init background blocks 
        m_helper->m_blocks.push_back({"Control", 20,20,180,320});
        m_helper->m_blocks.push_back({"Waveform", 220,20,180,320});
        m_helper->m_blocks.push_back({"LFO-Wave", 420,20,450,320});
        m_helper->m_blocks.push_back({"Unison", 20,360,650,150});
        m_helper->m_blocks.push_back({"Helper", 690,360,180,150});

        // init gui items --> make calls to createItem({});
        m_helper->createItem({"checkbox", m_name + "__active","",40,70,140,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__level","Volume",75,120,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__rate","Frequency",75,220,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"box", m_name + "__waveform_base","Base",240,50,140,55, VeNoSelect::Type::WaveTable});
        m_helper->createItem({"box", m_name + "__waveform_sec","Second",240,120,140,55, VeNoSelect::Type::WaveTable});
        m_helper->createItem({"checkbox", m_name + "__random_phase","Random Phase",240,185,140,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__waveform_mix","Mix",240,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__phase","Phase",320,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"lfowave", m_name,"LFO-Wave",440,60,410,240, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"box", m_name + "__detune_mode","Mode",130,410,180,65, VeNoSelect::Type::DetuneMode});
        m_helper->createItem({"slider", m_name + "__voices","Voices",360,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__detune_dense","Dense",450,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__detune_amount","Amount",540,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__detune_amount","Amount",540,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"textButton", "call_copy","Copy",745,400,70,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"textButton", "call_paste","Paste",745,450,70,30, VeNoSelect::Type::NoSelect});
    }
}