// This File is Auto-Generated by the json-to-gui.js!

#include "OscillatorPage.h"

namespace VeNo
{
    void OscillatorPage::setupGui ()
    {
        // init background blocks 
        m_helper->m_blocks.push_back({"Control", 20,20,180,230});
        m_helper->m_blocks.push_back({"Envelope", 220,20,450,150});
        m_helper->m_blocks.push_back({"Waveform", 690,20,180,320});
        m_helper->m_blocks.push_back({"Filter", 220,190,450,150});
        m_helper->m_blocks.push_back({"Unison", 220,360,650,150});
        m_helper->m_blocks.push_back({"Helper", 20,270,180,240});

        // init gui items --> make calls to createItem({});
        m_helper->createItem({"slider", m_name + "__panning","Pan",75,47,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__semitones","Semitones",40,147,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__cents","Fine",117,147,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__attack","Attack",260,60,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__decay","Decay",360,60,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__sustain","Sustain",460,60,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__release","Release",560,60,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"box", m_name + "__filter_type","Filter",240,245,180,55, VeNoSelect::Type::Filter});
        m_helper->createItem({"slider", m_name + "__filter_cutoff","Cutoff",450,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__filter_q","Q-Factor",550,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"box", m_name + "__waveform_base","Base",710,50,140,55, VeNoSelect::Type::WaveTable});
        m_helper->createItem({"box", m_name + "__waveform_sec","Second",710,120,140,55, VeNoSelect::Type::WaveTable});
        m_helper->createItem({"checkbox", m_name + "__random_phase","Random Phase",710,185,140,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__waveform_mix","Mix",700,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__phase","Phase",790,230,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"box", m_name + "__detune_mode","Mode",250,410,180,65, VeNoSelect::Type::DetuneMode});
        m_helper->createItem({"slider", m_name + "__voices","Voices",480,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__stereo","Stereo",570,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__detune_dense","Dense",660,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"slider", m_name + "__detune_amount","Amount",750,400,70,85, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"checkbox", m_name + "__active","",75,300,70,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"textButton", "call_solo","Solo",75,350,70,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"textButton", "call_copy","Copy",75,400,70,30, VeNoSelect::Type::NoSelect});
        m_helper->createItem({"textButton", "call_paste","Paste",75,450,70,30, VeNoSelect::Type::NoSelect});
    }
}