// This File is Auto-Generated by the json-to-gui.js!

#include "LFOPage.h"

namespace VeNo
{
    void LFOPage::setupGui ()
    {
        // init background blocks $b$

        // init gui items --> make calls to createItem({});$g$
    }
}