// This File is Auto-Generated by the json-to-gui.js!

#include "OscillatorPage.h"

namespace VeNo
{
    void OscillatorPage::setupGui ()
    {
        // init background blocks 
        m_blocks.push_back({"Control", 20,20,180,230});
        m_blocks.push_back({"Envelope", 220,20,450,150});
        m_blocks.push_back({"Waveform", 690,20,180,320});
        m_blocks.push_back({"Filter", 220,190,450,150});
        m_blocks.push_back({"Unison", 220,360,650,150});
        m_blocks.push_back({"Limiter", 20,270,180,240});

        // init gui items --> make calls to createItem({});
        createItem({"slider", m_name + "__panning","Pan",75,47,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__semitones","Semitones",40,147,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__cents","Fine",117,147,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__attack","Attack",260,60,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__decay","Decay",360,60,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__sustain","Sustain",460,60,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__release","Release",560,60,70,85, VeNoSelect::Type::NoSelect});
        createItem({"box", m_name + "__filter_type","Filter",240,245,180,55, VeNoSelect::Type::Filter});
        createItem({"slider", m_name + "__filter_cutoff","Cutoff",450,230,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__filter_q","Q-Factor",550,230,70,85, VeNoSelect::Type::NoSelect});
        createItem({"box", m_name + "__waveform_base","Base",710,50,140,40, VeNoSelect::Type::WaveTable});
        createItem({"box", m_name + "__waveform_sec","Second",710,120,140,40, VeNoSelect::Type::WaveTable});
        createItem({"checkbox", m_name + "__random_phase","Random Phase",745,185,65,30, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__waveform_mix","Mix",700,230,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__phase","Phase",790,230,70,85, VeNoSelect::Type::NoSelect});
        createItem({"box", m_name + "__detune_mode","Mode",250,410,180,50, VeNoSelect::Type::DetuneMode});
        createItem({"slider", m_name + "__voices","Voices",480,400,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__stereo","Stereo",570,400,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__detune_dense","Dense",660,400,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__detune_amount","Amount",750,400,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__limiter_mode","Limiter",75,300,70,85, VeNoSelect::Type::NoSelect});
        createItem({"slider", m_name + "__limiter_threshold","Threshold",75,400,70,85, VeNoSelect::Type::NoSelect});
    }
}